version: "3.9"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
